version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - '8080:8080'
      - '50000:50000'

  # React app service
  react-app:
    build: .
    ports:
      - '80:80' # Expose React app on port 80
    container_name: react-app
    networks:
      - monitoring

  # Prometheus service
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - monitoring

  # Grafana service
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      - monitoring
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin' # Set Grafana admin password
    depends_on:
      - prometheus # Ensure Prometheus is started before Grafana

networks:
  monitoring:
    driver: bridge
